import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  sheetBackground: {
    backgroundColor: '#115EA3',
    flex: 1,
  },
  contentContainer: {
    flex: 1,
    backgroundColor: '#115EA3',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    overflow: 'hidden',
    paddingTop: 0,
    paddingBottom: 36,
  },
  customHandle: {
    alignItems: 'center',
    paddingTop: 8,
    //backgroundColor: 'red',
  },
  indicator: {
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#D1D1D1',
  },
  title: {
    fontFamily: 'Roboto-Medium',
    paddingVertical: 1,
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
    lineHeight: 22,
    letterSpacing: -0.43,
    paddingLeft: 16,
    marginTop: 12,
  },
  inputContainer: {
    marginHorizontal: 16,
    marginTop: 12,
  },
  text: {
    fontFamily: 'Roboto-Regular',
    fontWeight: '400',
    color: '#FFFFFF',
    fontSize: 14,
    letterSpacing: -0.43,
    lineHeight: 22,
  },
  input: {
    marginTop: 10,
    borderRadius: 10,
    paddingLeft: 12,
    backgroundColor: '#0F6CBD',
    fontFamily: 'Roboto-Medium',
    fontWeight: '500',
    color: '#FFFFFF',
    fontSize: 14,
    lineHeight: 22,
    letterSpacing: -0.43,
    paddingVertical: 7,
  },
  brandSelectionContainer: {
    marginHorizontal: 18,
    marginTop: 16,
  },
  // brandsContainer: {
  //   flexDirection: 'row',
  //   marginTop: 40,
  //   marginBottom: 11,
  // },
  brandButton: {
    marginTop: 12,
    marginBottom: 11,
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 100,
    borderWidth: 1,
    borderColor: '#FFFFFF',
    marginRight: 12,
  },
  brandText: {
    color: '#FFFFFF',
    fontWeight: '600',
  },
  selectedBrandButton: {
    backgroundColor: '#FFFFFF',
  },

  selectedBrandText: {
    //backgroundColor: 'red',
    color: '#115EA3',
  },
  checkboxContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: 16,
    marginTop: 40,
    //borderRadius: 100,
    //backgroundColor: 'red',
  },
  checkbox: {
    width: 24,
    height: 24,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 100,
    marginRight: 12,
    //backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#FFFFFF',
  },
  checkboxChecked: {
    backgroundColor: '#FFFFFF',
  },
  checkboxTick: {
    color: '#115EA3',
  },
  submitButton: {
    backgroundColor: '#115EA3',
    paddingVertical: 13,
    alignItems: 'center',
    borderRadius: 10,
    marginTop: 24,
    marginHorizontal: 16,
    borderWidth: 1,
    borderColor: '#FFFFFF',
  },
  submitButtonText: {
    fontFamily: 'Roboto-Bold',
    color: '#FFFFFF',
    fontWeight: '700',
    fontSize: 16,
    lineHeight: 22,
    letterSpacing: -0.43,
  },
});

export default styles;
